-- Create sequences for auto-increment
CREATE SEQUENCE T_CLIENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_TRANSACTION_SEQ START WITH 1 INCREMENT BY 1;

-- Create table T_CLIENT with id, first_name, last_name and age columns
CREATE TABLE T_CLIENT (
    id NUMBER NOT NULL PRIMARY KEY,
    first_name VARCHAR2(250) NOT NULL,
    last_name VARCHAR2(250) NOT NULL,
    age NUMBER NOT NULL,
    phone_number VARCHAR2(250) NOT NULL,
    nationality VARCHAR2(250) NOT NULL
);

CREATE TABLE T_ACCOUNT (
    id NUMBER NOT NULL PRIMARY KEY,
    name VARCHAR2(250) NOT NULL,
    balance NUMBER NOT NULL,
    type VARCHAR2(250) NOT NULL,
    client_id NUMBER NOT NULL,
    FOREIGN KEY (client_id) REFERENCES T_CLIENT(id)
);

CREATE TABLE T_TRANSACTION (
    id NUMBER NOT NULL PRIMARY KEY,
    amount NUMBER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    account_id NUMBER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES T_ACCOUNT(id)
);
